# Setup
title:               'Музяблоки'
tagline:             'Новости музыкальных приложений для #iOS и #iPadOS. Новинки, обновления, обзоры.'
description:         '<a href="https://t.me/muzapples_chat">Русскоязычное iOS-коммьюнити в чате</a>.'
url:                 'https://necrobyte.github.io'
baseurl:             '/muzapples/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
